=== api-evangelist/accuweather/json-schema/accuweather-index-day-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/accuweather/refs/heads/main/json-schema/accuweather-index-day-schema.json",
  "title": "IndexDay",
  "description": "IndexDay schema from AccuWeather API",
  "type": "object",
  "properties": {
    "dayOfWeek": {
      "type": "string",
      "nullable": true
    },
    "shortDayOfWeek": {
      "type": "string",
      "nullable": true
    },
    "fullDayOfWeek": {
      "type": "string",
      "nullable": true
    },
    "epoch": {
      "type": "integer",
      "format": "int32",
      "nullable": true
    },
    "dateTime": {
      "type": "string",
      "nullable": true
    },
    "displayDate": {
      "type": "string",
      "nullable": true
    },
    "longDisplayDate": {
      "type": "string",
      "nullable": true
    },
    "value": {
      "type": "integer",
      "format": "int32"
    },
    "category": {
      "type": "string",
      "nullable": true
    },
    "color": {
      "type": "string",
      "nullable": true
    }
  },
  "additionalProperties": false
}

=== api-evangelist/accuweather/examples/accuweather-index-day-example.json
{
  "dayOfWeek": "example-string",
  "shortDayOfWeek": "example-string",
  "fullDayOfWeek": "example-string",
  "epoch": 66,
  "dateTime": "example-string",
  "displayDate": "example-string",
  "longDisplayDate": "-74.0060",
  "value": 84,
  "category": "example-string",
  "color": "example-string"
}
