=== api-evangelist/accuweather/json-schema/accuweather-ortb-site-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/accuweather/refs/heads/main/json-schema/accuweather-ortb-site-schema.json",
  "title": "OrtbSite",
  "description": "OrtbSite schema from AccuWeather API",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "nullable": true
    },
    "domain": {
      "type": "string",
      "nullable": true
    },
    "categories": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "nullable": true
    },
    "sectionCategories": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "nullable": true
    },
    "pageCategories": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "nullable": true
    },
    "keywords": {
      "type": "string",
      "nullable": true
    },
    "pageUrl": {
      "type": "string",
      "nullable": true
    },
    "referrerUrl": {
      "type": "string",
      "nullable": true
    },
    "isOptimizedForMobile": {
      "type": "boolean"
    },
    "hasPrivacyPolicy": {
      "type": "boolean"
    },
    "publisher": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "nullable": true
        },
        "domain": {
          "type": "string",
          "nullable": true
        },
        "categories": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "nullable": true
        }
      },
      "additionalProperties": false
    },
    "content": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string",
          "nullable": true
        },
        "url": {
          "type": "string",
          "nullable": true
        },
        "categories": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "nullable": true
        },
        "productQuality": {
          "type": "string",
          "nullable": true
        },
        "context": {
          "type": "string",
          "nullable": true
        },
        "keywords": {
          "type": "string",
          "nullable": true
        },
        "sourceRelationship": {
          "enum": [
            "Indirect",
            "Direct"
          ],
          "type": "string"
        },
        "language": {
          "type": "string",
          "nullable": true
        },
        "data": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "nullable": true
            },
            "extensions": {
              "type": "object",
              "additionalProperties": {
                "nullable": true
              },
              "nullable": true
            },
            "segments": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "nullable": true
                  },
                  "value": {
                    "type": "string",
                    "nullable": true
                  }
                },
                "additionalProperties": false
              },
              "nullable": true
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}

=== api-evangelist/accuweather/examples/accuweather-ortb-site-example.json
{
  "name": "New York",
  "domain": "example-string",
  "categories": [
    "example-string"
  ],
  "sectionCategories": [
    "example-string"
  ],
  "pageCategories": [
    "example-string"
  ],
  "keywords": "347628",
  "pageUrl": "https://www.accuweather.com/",
  "referrerUrl": "https://www.accuweather.com/",
  "isOptimizedForMobile": true,
  "hasPrivacyPolicy": true,
  "publisher": {
    "name": "New York",
    "domain": "example-string",
    "categories": [
      "example-string"
    ]
  },
  "content": {
    "title": "example-string",
    "url": "https://www.accuweather.com/",
    "categories": [
      "example-string"
    ],
    "productQuality": "example-string",
    "context": "Partly cloudy",
    "keywords": "347628",
    "sourceRelationship": "Indirect",
    "language": "example-string",
    "data": {
      "name": "New York"
    }
  }
}
