=== api-evangelist/accuweather/json-schema/accuweather-daily-index-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/accuweather/refs/heads/main/json-schema/accuweather-daily-index-schema.json",
  "title": "DailyIndex",
  "description": "DailyIndex schema from AccuWeather API",
  "type": "object",
  "properties": {
    "indexName": {
      "type": "string",
      "nullable": true
    },
    "indexType": {
      "enum": [
        "Unknown",
        "Running",
        "Jogging",
        "Hiking",
        "Biking",
        "Golf",
        "Tennis",
        "Skateboarding",
        "Concert",
        "KiteFlyingForecast",
        "BeachAndPool",
        "Sailing",
        "Stargazing",
        "FishingForecast",
        "Construction",
        "Skiing",
        "Heart",
        "Mosquito",
        "Dust",
        "SnowDays",
        "Hunting",
        "ArthritisDay",
        "ArthritisNight",
        "Asthma",
        "BBQ",
        "CommonColdForecast",
        "Flu",
        "Migraine",
        "LawnMowing",
        "Outdoor",
        "Sinus",
        "Flying",
        "FieldReadiness",
        "GrassGrowing",
        "SoilMoisture",
        "SchoolBusStop",
        "HomeEnergy",
        "FuelEconomy",
        "Composting",
        "ShoppingForecast",
        "Driving",
        "Thirst",
        "Frizz",
        "DogWalking",
        "COPD",
        "IndoorPest",
        "OutdoorPest",
        "AccuLumenBrightness",
        "MorningExercise",
        "Clothing",
        "CommonCold",
        "Comfort",
        "CarWashing",
        "HeatStroke",
        "UVIntensity",
        "ClothesDrying",
        "AirPollution",
        "Tourism",
        "AirConditioning",
        "Fishing",
        "SunProtection",
        "Shopping",
        "Rowing",
        "Traffic",
        "RoadConditions",
        "Umbrella",
        "HairDressing",
        "NightLife",
        "Beer",
        "KiteFlying",
        "Makeup",
        "WindChills",
        "Mood",
        "Exercise",
        "Dating",
        "Allergy",
        "Beach",
        "Sunglasses",
        "ShortPhrase",
        "Hypertension",
        "Dryness",
        "ApparentTemperature",
        "PolutionPrevention",
        "FoodPoisoning",
        "WindChillDescending",
        "Heat",
        "Discomfort",
        "UVDescending",
        "PipeFreeze",
        "AtmosphericDispersion",
        "HeatSensitivityGeneral",
        "HeatSensitivityElderly",
        "HeatSensitivityChildren",
        "HeatSensitivityOutdoorWorking",
        "HeatSensitivityFarming",
        "HeatSensitivityGreenhouse",
        "HeatSensitivityVulnerableResidential",
        "AsthmaAndLungDisorder",
        "Stroke",
        "SkinSensitivity",
        "CommonColdDescending",
        "TreePollenLevels",
        "PinePollen",
        "WeedPollenLevels",
        "Arthritis",
        "OutdoorHomeGarden",
        "SoilHomeGarden",
        "FieldHomeGarden",
        "UV",
        "TreePollen",
        "RagweedPollen",
        "MoldPollen",
        "GrassPollen",
        "AirQuality",
        "FlightDelay",
        "IndoorActivity"
      ],
      "type": "string"
    },
    "days": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "dayOfWeek": {
            "type": "string",
            "nullable": true
          },
          "shortDayOfWeek": {
            "type": "string",
            "nullable": true
          },
          "fullDayOfWeek": {
            "type": "string",
            "nullable": true
          },
          "epoch": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "dateTime": {
            "type": "string",
            "nullable": true
          },
          "displayDate": {
            "type": "string",
            "nullable": true
          },
          "longDisplayDate": {
            "type": "string",
            "nullable": true
          },
          "value": {
            "type": "integer",
            "format": "int32"
          },
          "category": {
            "type": "string",
            "nullable": true
          },
          "color": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "nullable": true
    },
    "activityType": {
      "enum": [
        "Allergies",
        "Health",
        "OutdoorActivities",
        "TravelCommute",
        "HomeGarden",
        "Pests"
      ],
      "type": "string"
    }
  },
  "additionalProperties": false
}

=== api-evangelist/accuweather/examples/accuweather-daily-index-example.json
{
  "indexName": "New York",
  "indexType": "UVIntensity",
  "days": [
    {
      "dayOfWeek": "example-string",
      "shortDayOfWeek": "example-string",
      "fullDayOfWeek": "example-string",
      "epoch": 86,
      "dateTime": "example-string",
      "displayDate": "example-string",
      "longDisplayDate": "-74.0060",
      "value": 47,
      "category": "example-string",
      "color": "example-string"
    }
  ],
  "activityType": "OutdoorActivities"
}
