=== api-evangelist/accuweather/json-schema/accuweather-current-conditions-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/accuweather/refs/heads/main/json-schema/accuweather-current-conditions-schema.json",
  "title": "CurrentConditions",
  "description": "CurrentConditions schema from AccuWeather API",
  "type": "object",
  "properties": {
    "extended": {
      "type": "object",
      "properties": {
        "ceiling": {
          "type": "string",
          "nullable": true
        },
        "cloudCover": {
          "type": "string",
          "nullable": true
        },
        "dewPoint": {
          "type": "string",
          "nullable": true
        },
        "gusts": {
          "type": "string",
          "nullable": true
        },
        "wind": {
          "type": "string",
          "nullable": true
        },
        "windValue": {
          "type": "number",
          "format": "double",
          "nullable": true
        },
        "windDegrees": {
          "type": "number",
          "format": "double",
          "nullable": true
        },
        "windDirection": {
          "type": "string",
          "nullable": true
        },
        "humidity": {
          "type": "string",
          "nullable": true
        },
        "humidityValue": {
          "type": "integer",
          "format": "int32",
          "nullable": true
        },
        "indoorHumidity": {
          "type": "string",
          "nullable": true
        },
        "indoorHumidityCategory": {
          "type": "string",
          "nullable": true
        },
        "precipitation": {
          "type": "string",
          "nullable": true
        },
        "pressure": {
          "type": "string",
          "nullable": true
        },
        "ice": {
          "type": "string",
          "nullable": true
        },
        "rain": {
          "type": "string",
          "nullable": true
        },
        "snow": {
          "type": "string",
          "nullable": true
        },
        "thunderstormProbability": {
          "type": "string",
          "nullable": true
        },
        "uv": {
          "type": "object",
          "properties": {
            "category": {
              "type": "string",
              "nullable": true
            },
            "value": {
              "type": "number",
              "format": "float"
            }
          },
          "additionalProperties": false
        },
        "visibility": {
          "type": "string",
          "nullable": true
        },
        "precipSummary": {
          "type": "object",
          "properties": {
            "past12Hours": {
              "type": "string",
              "nullable": true
            },
            "past18Hours": {
              "type": "string",
              "nullable": true
            },
            "past24Hours": {
              "type": "string",
              "nullable": true
            },
            "past3Hours": {
              "type": "string",
              "nullable": true
            },
            "past6Hours": {
              "type": "string",
              "nullable": true
            },
            "past9Hours": {
              "type": "string",
              "nullable": true
            },
            "pastHour": {
              "type": "string",
              "nullable": true
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "isDayTime": {
      "type": "boolean"
    },
    "iconCode": {
      "type": "integer",
      "format": "int32"
    },
    "now": {
      "type": "string",
      "nullable": true
    },
    "phrase": {
      "type": "string",
      "nullable": true
    },
    "realFeel": {
      "type": "string",
      "nullable": true
    },
    "realFeelShade": {
      "type": "string",
      "nullable": true
    },
    "temperature": {
      "type": "string",
      "nullable": true
    },
    "temperatureValue": {
      "type": "number",
      "format": "float",
      "nullable": true
    },
    "realFeelValue": {
      "type": "number",
      "format": "float",
      "nullable": true
    },
    "realFeelShadeValue": {
      "type": "number",
      "format": "float",
      "nullable": true
    },
    "realFeelPhrase": {
      "type": "string",
      "nullable": true
    },
    "realFeelShadePhrase": {
      "type": "string",
      "nullable": true
    },
    "apparentTempImperial": {
      "type": "number",
      "format": "float",
      "nullable": true
    },
    "windSpeedImperial": {
      "type": "number",
      "format": "float",
      "nullable": true
    }
  },
  "additionalProperties": false
}

=== api-evangelist/accuweather/examples/accuweather-current-conditions-example.json
{
  "extended": {
    "ceiling": "example-string",
    "cloudCover": "example-string",
    "dewPoint": "example-string",
    "gusts": "example-string",
    "wind": "example-string",
    "windValue": 12.5,
    "windDegrees": 12.5,
    "windDirection": "example-string",
    "humidity": "500123",
    "humidityValue": 54,
    "indoorHumidity": "500123",
    "indoorHumidityCategory": "500123",
    "precipitation": "example-string",
    "pressure": "example-string",
    "ice": "example-string",
    "rain": "example-string",
    "snow": "example-string",
    "thunderstormProbability": "example-string",
    "uv": {
      "category": "example-string",
      "value": 12.9
    },
    "visibility": "example-string",
    "precipSummary": {
      "past12Hours": "example-string",
      "past18Hours": "example-string",
      "past24Hours": "example-string",
      "past3Hours": "example-string",
      "past6Hours": "example-string",
      "past9Hours": "example-string",
      "pastHour": "example-string"
    }
  },
  "isDayTime": true,
  "iconCode": 6,
  "now": "example-string",
  "phrase": "Partly cloudy",
  "realFeel": "example-string",
  "realFeelShade": "example-string",
  "temperature": "example-string",
  "temperatureValue": 72.5,
  "realFeelValue": 72.5,
  "realFeelShadeValue": 72.5,
  "realFeelPhrase": "Partly cloudy",
  "realFeelShadePhrase": "Partly cloudy",
  "apparentTempImperial": 72.5,
  "windSpeedImperial": 12.5
}
