=== api-evangelist/accuweather/json-schema/accuweather-confidence-range-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/accuweather/refs/heads/main/json-schema/accuweather-confidence-range-schema.json",
  "title": "ConfidenceRange",
  "description": "ConfidenceRange schema from AccuWeather API",
  "type": "object",
  "properties": {
    "lower": {
      "type": "object",
      "properties": {
        "displayAmount": {
          "type": "string",
          "nullable": true
        },
        "low": {
          "type": "object",
          "properties": {
            "value": {
              "type": "number",
              "format": "float",
              "nullable": true
            },
            "unit": {
              "type": "string",
              "nullable": true
            },
            "unitType": {
              "type": "integer",
              "format": "int32"
            }
          },
          "additionalProperties": false
        },
        "high": {
          "type": "object",
          "properties": {
            "value": {
              "type": "number",
              "format": "float",
              "nullable": true
            },
            "unit": {
              "type": "string",
              "nullable": true
            },
            "unitType": {
              "type": "integer",
              "format": "int32"
            }
          },
          "additionalProperties": false
        },
        "probability": {
          "type": "integer",
          "format": "int32",
          "nullable": true
        },
        "phrase": {
          "type": "string",
          "nullable": true
        }
      },
      "additionalProperties": false
    },
    "low": {
      "type": "object",
      "properties": {
        "displayAmount": {
          "type": "string",
          "nullable": true
        },
        "low": {
          "type": "object",
          "properties": {
            "value": {
              "type": "number",
              "format": "float",
              "nullable": true
            },
            "unit": {
              "type": "string",
              "nullable": true
            },
            "unitType": {
              "type": "integer",
              "format": "int32"
            }
          },
          "additionalProperties": false
        },
        "high": {
          "type": "object",
          "properties": {
            "value": {
              "type": "number",
              "format": "float",
              "nullable": true
            },
            "unit": {
              "type": "string",
              "nullable": true
            },
            "unitType": {
              "type": "integer",
              "format": "int32"
            }
          },
          "additionalProperties": false
        },
        "probability": {
          "type": "integer",
          "format": "int32",
          "nullable": true
        },
        "phrase": {
          "type": "string",
          "nullable": true
        }
      },
      "additionalProperties": false
    },
    "likely": {
      "type": "object",
      "properties": {
        "displayAmount": {
          "type": "string",
          "nullable": true
        },
        "low": {
          "type": "object",
          "properties": {
            "value": {
              "type": "number",
              "format": "float",
              "nullable": true
            },
            "unit": {
              "type": "string",
              "nullable": true
            },
            "unitType": {
              "type": "integer",
              "format": "int32"
            }
          },
          "additionalProperties": false
        },
        "high": {
          "type": "object",
          "properties": {
            "value": {
              "type": "number",
              "format": "float",
              "nullable": true
            },
            "unit": {
              "type": "string",
              "nullable": true
            },
            "unitType": {
              "type": "integer",
              "format": "int32"
            }
          },
          "additionalProperties": false
        },
        "probability": {
          "type": "integer",
          "format": "int32",
          "nullable": true
        },
        "phrase": {
          "type": "string",
          "nullable": true
        }
      },
      "additionalProperties": false
    },
    "high": {
      "type": "object",
      "properties": {
        "displayAmount": {
          "type": "string",
          "nullable": true
        },
        "low": {
          "type": "object",
          "properties": {
            "value": {
              "type": "number",
              "format": "float",
              "nullable": true
            },
            "unit": {
              "type": "string",
              "nullable": true
            },
            "unitType": {
              "type": "integer",
              "format": "int32"
            }
          },
          "additionalProperties": false
        },
        "high": {
          "type": "object",
          "properties": {
            "value": {
              "type": "number",
              "format": "float",
              "nullable": true
            },
            "unit": {
              "type": "string",
              "nullable": true
            },
            "unitType": {
              "type": "integer",
              "format": "int32"
            }
          },
          "additionalProperties": false
        },
        "probability": {
          "type": "integer",
          "format": "int32",
          "nullable": true
        },
        "phrase": {
          "type": "string",
          "nullable": true
        }
      },
      "additionalProperties": false
    },
    "higher": {
      "type": "object",
      "properties": {
        "displayAmount": {
          "type": "string",
          "nullable": true
        },
        "low": {
          "type": "object",
          "properties": {
            "value": {
              "type": "number",
              "format": "float",
              "nullable": true
            },
            "unit": {
              "type": "string",
              "nullable": true
            },
            "unitType": {
              "type": "integer",
              "format": "int32"
            }
          },
          "additionalProperties": false
        },
        "high": {
          "type": "object",
          "properties": {
            "value": {
              "type": "number",
              "format": "float",
              "nullable": true
            },
            "unit": {
              "type": "string",
              "nullable": true
            },
            "unitType": {
              "type": "integer",
              "format": "int32"
            }
          },
          "additionalProperties": false
        },
        "probability": {
          "type": "integer",
          "format": "int32",
          "nullable": true
        },
        "phrase": {
          "type": "string",
          "nullable": true
        }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}

=== api-evangelist/accuweather/examples/accuweather-confidence-range-example.json
{
  "lower": {
    "displayAmount": "example-string",
    "low": {
      "value": 85.0,
      "unit": "Imperial",
      "unitType": 5
    },
    "high": {
      "value": 52.1,
      "unit": "Imperial",
      "unitType": 46
    },
    "probability": 56,
    "phrase": "Partly cloudy"
  },
  "low": {
    "displayAmount": "example-string",
    "low": {
      "value": 99.5,
      "unit": "Imperial",
      "unitType": 57
    },
    "high": {
      "value": 63.7,
      "unit": "Imperial",
      "unitType": 94
    },
    "probability": 35,
    "phrase": "Partly cloudy"
  },
  "likely": {
    "displayAmount": "example-string",
    "low": {
      "value": 53.2,
      "unit": "Imperial",
      "unitType": 91
    },
    "high": {
      "value": 19.9,
      "unit": "Imperial",
      "unitType": 48
    },
    "probability": 0,
    "phrase": "Partly cloudy"
  },
  "high": {
    "displayAmount": "example-string",
    "low": {
      "value": 8.8,
      "unit": "Imperial",
      "unitType": 40
    },
    "high": {
      "value": 39.7,
      "unit": "Imperial",
      "unitType": 2
    },
    "probability": 32,
    "phrase": "Partly cloudy"
  },
  "higher": {
    "displayAmount": "example-string",
    "low": {
      "value": 30.2,
      "unit": "Imperial",
      "unitType": 66
    },
    "high": {
      "value": 7.2,
      "unit": "Imperial",
      "unitType": 2
    },
    "probability": 88,
    "phrase": "Partly cloudy"
  }
}
