=== api-evangelist/accuweather/json-schema/accuweather-daily-forecast-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/accuweather/refs/heads/main/json-schema/accuweather-daily-forecast-schema.json",
  "title": "DailyForecast",
  "description": "DailyForecast schema from AccuWeather API",
  "type": "object",
  "properties": {
    "dayOfWeek": {
      "type": "string",
      "nullable": true
    },
    "shortDayOfWeek": {
      "type": "string",
      "nullable": true
    },
    "fullDayOfWeek": {
      "type": "string",
      "nullable": true
    },
    "epoch": {
      "type": "integer",
      "format": "int32",
      "nullable": true
    },
    "dateTime": {
      "type": "string",
      "nullable": true
    },
    "displayDate": {
      "type": "string",
      "nullable": true
    },
    "longDisplayDate": {
      "type": "string",
      "nullable": true
    },
    "hasAlert": {
      "type": "boolean"
    },
    "day": {
      "type": "object",
      "properties": {
        "temperature": {
          "type": "number",
          "format": "float",
          "nullable": true
        },
        "displayTemperature": {
          "type": "string",
          "nullable": true
        },
        "icon": {
          "type": "integer",
          "format": "int32"
        },
        "iconPhrase": {
          "type": "string",
          "nullable": true
        },
        "phrase": {
          "type": "string",
          "nullable": true
        },
        "longPhrase": {
          "type": "string",
          "nullable": true
        },
        "precip": {
          "type": "string",
          "nullable": true
        },
        "realFeelValue": {
          "type": "number",
          "format": "float",
          "nullable": true
        }
      },
      "additionalProperties": false
    },
    "night": {
      "type": "object",
      "properties": {
        "temperature": {
          "type": "number",
          "format": "float",
          "nullable": true
        },
        "displayTemperature": {
          "type": "string",
          "nullable": true
        },
        "icon": {
          "type": "integer",
          "format": "int32"
        },
        "iconPhrase": {
          "type": "string",
          "nullable": true
        },
        "phrase": {
          "type": "string",
          "nullable": true
        },
        "longPhrase": {
          "type": "string",
          "nullable": true
        },
        "precip": {
          "type": "string",
          "nullable": true
        },
        "realFeelValue": {
          "type": "number",
          "format": "float",
          "nullable": true
        }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}

=== api-evangelist/accuweather/examples/accuweather-daily-forecast-example.json
{
  "dayOfWeek": "example-string",
  "shortDayOfWeek": "example-string",
  "fullDayOfWeek": "example-string",
  "epoch": 93,
  "dateTime": "example-string",
  "displayDate": "example-string",
  "longDisplayDate": "-74.0060",
  "hasAlert": true,
  "day": {
    "temperature": 72.5,
    "displayTemperature": "example-string",
    "icon": 6,
    "iconPhrase": "Partly cloudy",
    "phrase": "Partly cloudy",
    "longPhrase": "-74.0060",
    "precip": "example-string",
    "realFeelValue": 72.5
  },
  "night": {
    "temperature": 72.5,
    "displayTemperature": "example-string",
    "icon": 6,
    "iconPhrase": "Partly cloudy",
    "phrase": "Partly cloudy",
    "longPhrase": "-74.0060",
    "precip": "example-string",
    "realFeelValue": 72.5
  }
}
